/*
# Create storage bucket for e-books and sample files

1. Storage
- Create a private (non-public) storage bucket named "ebooks" for storing PDF/ePub files.
- Files in this bucket are NOT publicly accessible — they can only be accessed via signed URLs generated by the secure-download edge function.

2. Notes
- The bucket is private to prevent direct asset leaks.
- The secure-download edge function generates time-limited signed URLs (1 hour validity) for verified buyers.
*/

INSERT INTO storage.buckets (id, name, public)
VALUES ('ebooks', 'ebooks', false)
ON CONFLICT (id) DO NOTHING;

-- Allow the service role (edge functions) to read from the bucket
-- The secure-download function uses the service role key, so it bypasses RLS
-- No additional storage policies needed since we use service role for signed URL generation
